version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 2
    directory: "/"
    schedule:
      interval: monthly
      day: monday

  - package-ecosystem: "cargo"
    open-pull-requests-limit: 2
    directory: /
    schedule:
      interval: weekly
      timezone: "05:00 UTC"
      day: monday
