version: '3'
services:
  cc_alice:
    container_name: cc-alice
    image: "centrifugeio/centrifuge-chain:${CC_DOCKER_TAG:-test-main-latest}"
    platform: "linux/amd64"
    ports:
      - "30355:30333"
      - "9946:9933"
    volumes:
      - type: bind
        source: ./res/rococo-local.json
        target: /chainspec.json
        read_only: true
    command: >
      --chain="${PARA_CHAIN_SPEC:-development}" 
      --alice
      --parachain-id="2000"
      --wasm-execution=compiled
      --execution=wasm
      --port=30333
      --rpc-port=9933
      --rpc-external
      --rpc-cors all
      --rpc-methods=Unsafe
      --log="main,info,xcm=trace,xcm-executor=trace"
      --database=auto
      -- 
      --wasm-execution=compiled 
      --execution=wasm
      --chain=/chainspec.json 
      --bootnodes="/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDLpRT9KFo6pKdkmdQQt599tmqVYpoeiHemY32Gf4RUpp"
      --bootnodes="/ip4/127.0.0.1/tcp/30344/p2p/12D3KooWKpaJZbNymrZmKG6BNNDC58z8p9YKDXfZtyhEjktgtph4"
