name: Docker Build
on:
  push:
    branches: [main, 'release-v**']
  pull_request:
    paths:
      - ".github/workflows/build-docker.yml"
      - "Dockerfile"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}${{ github.ref == '/refs/heads/main' && github.sha || 'false' }}
  cancel-in-progress: true
env:
  RUST_TOOLCHAIN: "1.66"
jobs:
  docker:
    strategy:
      matrix:
        target: [ release, test ]
    runs-on: ubuntu-latest-4-cores
    env:
      WORKFLOW_TAG: ${{ github.event.inputs.docker_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Free space
      # https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930
        run: |
          sudo rm -rf /usr/share/dotnet
          # sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: check available docker space
        run: |
          docker volume ls
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: echo "NOW=$(date -u +%y-%m-%d)" >> $GITHUB_ENV

      - name: Setup docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: centrifugeio/centrifuge-chain
          flavor: |
            suffix=-${{ env.NOW }}
            # latest=auto is already default, but the logic needs a value at the end and '' isn't valid
            ${{ matrix.target == 'test' && 'prefix=test-' || 'latest=auto' }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=edge

      - name: Build and push centrifugeio/centrifuge-chain
        uses: docker/build-push-action@v5
        env:
          FEATURES: ${{ matrix.target == 'test' && '"fast-runtime"' || '' }}
        with:
          context: .
          file: ./docker/centrifuge-chain/Dockerfile
          push: ${{ github.ref == '/refs/heads/main' && true || false }}
          tags: ${{ steps.meta.outputs.tags }}
          # Cache options:
          # https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=registry,ref=centrifugeio/centrifuge-chain
          # https://docs.docker.com/build/cache/backends/inline/
          cache-to: inline

      - name: Update DockerHub descriptions
        if: contains(github.ref, 'refs/tags/release-v')
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: centrifuge/centrifuge-chain
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true

      - if: failure()
        name: Check available space after build failed
        run: |
          docker volume ls
          df -h