name: nix-build
on:
  pull_request:
  push:
    branches: [parachain]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.6.0/install
      - uses: cachix/cachix-action@v10
        with:
          name: centrifuge-chain
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build centrifuge-chain
        # The last bit is a work-around an issue in nix,
        # which can be removed once 2.8 is released.
        # Cf. https://github.com/NixOS/nix/pull/5758
        run: nix build --no-allow-dirty -L .\?rev=$(git rev-parse HEAD)
