on:
  push:
    branches: [main, 'release-v**']
  pull_request:
name: Tests
jobs:
  tests:
    name: ${{ matrix.target }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [tests, integration]
    runs-on: ${{ matrix.os }}
    env:
      RUST_TOOLCHAIN: "nightly-2022-11-14"
    steps:
      - name: Prep build on Ubuntu
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          echo "Pre cleanup"
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          rm -rf /usr/share/dotnet/
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get install protobuf-compiler
          df -h
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
      - name: Run tests
        run: ./ci/script.sh
        env:
          TARGET: ${{ matrix.target }}

